/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasi_penjualan_sederhana;

import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Joji Sinaga
 */
public class Login extends javax.swing.JFrame {
    private PreparedStatement stat; // untuk menampung atau mengambil dari sql
    private ResultSet rs; // untuk isian inputan
    //variabel koneksi
    koneksi k = new koneksi();

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        // koneksikan file koneksi dengan xampp
        k.connect();
    }
    
    //bust class sesuai struktur yang telah dibuat di database tabel user
    class user{
            int id_user;
            int id_level;
            String username;
            String password;
            String nama_user;
            
            // constractor
            
            public user(){
                this.id_user = 0;
                this.username = text_username.getText();
                this.password = text_password.getText();
                this.nama_user = "";
                this.id_level = 0;
            }
      }
                 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        text_password = new javax.swing.JPasswordField();
        text_username = new javax.swing.JTextField();
        btn_login = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOGIN.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USERNAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 231, -1, -1));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PASSWORD");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 259, -1, -1));

        text_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_passwordActionPerformed(evt);
            }
        });
        text_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_passwordKeyPressed(evt);
            }
        });
        getContentPane().add(text_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 256, 418, -1));
        getContentPane().add(text_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 228, 418, -1));

        btn_login.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_login.setText("LOGIN");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 290, 147, 38));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mari, silakan login!");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rdr2jpg.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-790, -240, 1510, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // Buat algoritma Login sesuai level yang sudah ditentukan
        user u = new user(); //ini untuk menampung isian username dan password
        try{
            //mengambil terlebih dahulu dari sqlnya
            this.stat = k.getCon().prepareStatement("select * from user where + username='"+u.username+"' " + "and password = '"+u.password+"' ");
            //untuk menampung isian yang sudah kita ambil dari sql
            this.rs = this.stat.executeQuery();
            while (rs.next()){
                u.id_level = rs.getInt("id_level");
        }
            if (u.id_level == 0){
                JOptionPane.showMessageDialog(null, "Akun Tidak Ditemukan");
            } else {
                switch(u.id_level){
                    case 1 :
                        Registrasi reg = new Registrasi();
                        reg.setVisible(true);
                        this.setVisible(false);
                        break;
                    case 2 :
                        Transaksi tran = new Transaksi();
                        tran.setVisible(true);
                        this.setVisible(false);
                        break;
                    case 3 : //owner
                        Transaksi tran2 = new Transaksi();
                        tran2.setVisible(true);
                        this.setVisible(false);
                        tran2.transbtn_cetlap.setEnabled(true);
                        break;
                    case 4 : //pelanggan
                        Barang brng = new Barang();
                        brng.setVisible(true);
                        this.setVisible(false);
                        brng.brgbtn_log.setEnabled(true);
                        break;
                    case 5 :
                        Login log = new Login();
                        log.setVisible(false);
                        this.setVisible(true);
                }
            }
            //untuk menunjukan errornya di mana
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void text_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_passwordActionPerformed

    private void text_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_passwordKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            user u = new user(); //ini untuk menampung isian username dan password
        try{
            //mengambil terlebih dahulu dari sqlnya
            this.stat = k.getCon().prepareStatement("select * from user where + username='" +u.username+"'" + "and password='"+u.password+"';");
            //untuk menampung isian yang sudah kita ambil dari sql
            this.rs = this.stat.executeQuery();
            while (rs.next()){
                u.id_level = rs.getInt("id_level");
        }
            if (u.id_level == 0){
                JOptionPane.showConfirmDialog(null, "Akun Tidak Ditemukan");
            } else {
                switch(u.id_level){
                    case 1 :
                        Registrasi reg = new Registrasi();
                        reg.setVisible(true);
                        this.setVisible(false);
                        break;
                    case 2 :
                        Transaksi tran = new Transaksi();
                        tran.setVisible(true);
                        this.setVisible(false);
                        break;
                    case 3 : //owner
                        Transaksi tran2 = new Transaksi();
                        tran2.setVisible(true);
                        this.setVisible(false);
                        tran2.transbtn_cetlap.setEnabled(true);
                        break;
                    case 4 :
                        Barang brng = new Barang();
                        brng.setVisible(true);
                        this.setVisible(false);
                        brng.brgbtn_log.setEnabled(true);
                        break;
                    case 5 :
                        Login log = new Login();
                        log.setVisible(false);
                        this.setVisible(true);
                }
            }
            //untuk menunjukan errornya di mana
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    }//GEN-LAST:event_text_passwordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JPasswordField text_password;
    private javax.swing.JTextField text_username;
    // End of variables declaration//GEN-END:variables
}
