/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasi_penjualan_sederhana;

import java.io.File;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import javax.swing.JOptionPane;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Joji Sinaga
 */
public class Transaksi extends javax.swing.JFrame {
    
    private DefaultTableModel model = null;
    private PreparedStatement stat;
    private ResultSet rs;
    koneksi k = new koneksi();
//    // Variables declaration - do not modify                     
//    private javax.swing.JButton transbtn_cetlap;
//    // End of variables declaration   
//
//    // Method untuk memberikan akses ke button cetak laporan
//    public javax.swing.JButton getButtonCetakLaporan() {
//        return transbtn_cetlap;
//    }

    /**
     * Creates new form Transaksi
     */
    public Transaksi() {
        initComponents();
        k.connect();
        refreshTable();
        refreshCombo();
    }
    
    class transaksi extends Transaksi{
        int id_transaksi, id_barang, harga, jumlah_beli, total_bayar;
        String nama_pelanggan, tanggal, nama_barang;
        
        public transaksi(){
            this.nama_pelanggan = txt_pelang.getText();
            String combo = bobox_idbar.getSelectedItem().toString();
            String[] arr = combo.split(":");
            this.id_barang = Integer.parseInt(arr[0]);
            try{
                Date date = txt_tgl.getDate();
                DateFormat dateformat = new SimpleDateFormat("YYYY-MM-dd");
                this.tanggal = dateformat.format(date);
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            this.nama_barang = arr[1];
            this.harga = Integer.parseInt(arr[2]);
            this.jumlah_beli = Integer.parseInt(txt_jumbar.getText());
            this.total_bayar = this.harga * this.jumlah_beli;
        }
    }
    
    public void refreshTable(){
        model = new DefaultTableModel();
        model.addColumn("ID Transaksi");
        model.addColumn("Nama Pelanggan");
        model.addColumn("ID Barang");
        model.addColumn("Tanggal");
        model.addColumn("Nama Barang");
        model.addColumn("Harga");
        model.addColumn("Jumlah Beli");
        model.addColumn("Total Bayar");
        transtbl.setModel(model);
    
    
    try{
    this.stat = k.getCon().prepareStatement("select * from transaksi");
    this.rs = this.stat.executeQuery();
    while (rs.next()){
        Object[] data ={
            rs.getString(1),
            rs.getString(2),
            rs.getString(3),
            rs.getString(4),
            rs.getString(5),
            rs.getString(6),
            rs.getString(7),
            rs.getString(8)
        };
            model.addRow(data);
        }
    }catch (Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
    }
    //agar isian setelah diisi tidak kosong lagi
    txt_idtrans.setText("");
    txt_pelang.setText("");
    txt_jumbar.setText("");
    txt_totbar.setText("");
}
    
    public void refreshCombo(){
        try{
            this.stat = k.getCon().prepareStatement("select * from barang " + "where status='Tersedia'");
            this.rs = this.stat.executeQuery();
            while(rs.next()){
                bobox_idbar.addItem(rs.getString("id_barang")+":"+rs.getString("nama_barang")+":"+rs.getString("harga"));
  
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDayChooser1 = new com.toedter.calendar.JDayChooser();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jDayChooser2 = new com.toedter.calendar.JDayChooser();
        jCalendar2 = new com.toedter.calendar.JCalendar();
        jScrollPane1 = new javax.swing.JScrollPane();
        transtbl = new javax.swing.JTable();
        transbtn_in = new javax.swing.JButton();
        transbtn_up = new javax.swing.JButton();
        transbtn_del = new javax.swing.JButton();
        transbtn_cetlap = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        transbtn_log = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_idtrans = new javax.swing.JTextField();
        txt_pelang = new javax.swing.JTextField();
        bobox_idbar = new javax.swing.JComboBox<>();
        txt_jumbar = new javax.swing.JTextField();
        txt_totbar = new javax.swing.JTextField();
        txt_tgl = new com.toedter.calendar.JDateChooser();
        btn_lihbar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        transtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        transtbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transtblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(transtbl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 390, 523, -1));

        transbtn_in.setText("INPUT");
        transbtn_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transbtn_inActionPerformed(evt);
            }
        });
        getContentPane().add(transbtn_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 349, 89, -1));

        transbtn_up.setText("UPDATE");
        transbtn_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transbtn_upActionPerformed(evt);
            }
        });
        getContentPane().add(transbtn_up, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 349, 94, -1));

        transbtn_del.setText("DELETE");
        transbtn_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transbtn_delActionPerformed(evt);
            }
        });
        getContentPane().add(transbtn_del, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 349, 97, -1));

        transbtn_cetlap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        transbtn_cetlap.setText("Cetak Laporan");
        transbtn_cetlap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transbtn_cetlapActionPerformed(evt);
            }
        });
        getContentPane().add(transbtn_cetlap, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 346, 169, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("TRANSAKSI");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 6, -1, -1));

        transbtn_log.setText("LOGOUT");
        transbtn_log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transbtn_logActionPerformed(evt);
            }
        });
        getContentPane().add(transbtn_log, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("ID Transaksi");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 53, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Nama Pelanggan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 93, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("ID Barang");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 145, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Tanggal");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 191, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Jumlah Beli");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 245, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Total Bayar");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 292, -1, -1));

        txt_idtrans.setEnabled(false);
        txt_idtrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idtransActionPerformed(evt);
            }
        });
        getContentPane().add(txt_idtrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 53, 358, -1));
        getContentPane().add(txt_pelang, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 93, 358, -1));

        bobox_idbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bobox_idbarActionPerformed(evt);
            }
        });
        getContentPane().add(bobox_idbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 145, 223, -1));
        getContentPane().add(txt_jumbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 245, 358, -1));

        txt_totbar.setEnabled(false);
        txt_totbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totbarActionPerformed(evt);
            }
        });
        getContentPane().add(txt_totbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 292, 358, -1));
        getContentPane().add(txt_tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 191, 358, -1));

        btn_lihbar.setText("Lihat Barang");
        btn_lihbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lihbarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_lihbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 145, 117, -1));

        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void transbtn_cetlapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transbtn_cetlapActionPerformed
        // TODO add your handling code here:
        try{
            File namafile = new File("src/Laporan/Laporan_Transaksi.jasper");
            JasperPrint jp = JasperFillManager.fillReport(namafile.getPath(), null, k.getCon());
            JasperViewer.viewReport(jp,false);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_transbtn_cetlapActionPerformed

    private void txt_idtransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idtransActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idtransActionPerformed

    private void transbtn_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transbtn_inActionPerformed
        // TODO add your handling code here:
        try{
            transaksi tran = new transaksi();
            txt_totbar.setText(""+tran.total_bayar);
            this.stat = k.getCon().prepareStatement("insert into transaksi values(?,?,?,?,?,?,?,?)");
            this.stat.setInt(1, 0);
            this.stat.setString(2, tran.nama_pelanggan);
            this.stat.setInt(3, tran.id_barang);
            this.stat.setString(4, tran.tanggal);
            this.stat.setString(5, tran.nama_barang);
            this.stat.setInt(6, tran.harga);
            this.stat.setInt(7, tran.jumlah_beli);
            this.stat.setInt(8, tran.total_bayar);
            //untuk memulihkan pop up tampilan
            int pilihan = JOptionPane.showConfirmDialog(null, 
                    "Tanggal: "+tran.tanggal+
                    "\nNama Pelanggan: "+tran.nama_pelanggan+
                    "\nPemblian: "+tran.jumlah_beli+" "+tran.nama_barang+
                    "\nTotal Bayar: "+tran.total_bayar+"\n",
                    "Tambahkan Transaksi?",
                    JOptionPane.YES_NO_OPTION);
                if(pilihan == JOptionPane.YES_OPTION){
                    this.stat.executeUpdate();
                    refreshTable();
                }else if(pilihan == JOptionPane.NO_OPTION){
                        refreshTable();
                }
            }catch (Exception e){
                    JOptionPane.showMessageDialog(null, e.getMessage());
            }
    }//GEN-LAST:event_transbtn_inActionPerformed

    private void transtblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transtblMouseClicked
        // TODO add your handling code here:
        txt_idtrans.setText(model.getValueAt(transtbl.getSelectedRow(), 0).toString());
        txt_pelang.setText(model.getValueAt(transtbl.getSelectedRow(), 1).toString());
        txt_jumbar.setText(model.getValueAt(transtbl.getSelectedRow(), 6).toString());
        txt_totbar.setText(model.getValueAt(transtbl.getSelectedRow(), 7).toString());
    }//GEN-LAST:event_transtblMouseClicked

    private void transbtn_logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transbtn_logActionPerformed
        // TODO add your handling code here:
        Login l = new Login();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_transbtn_logActionPerformed

    private void transbtn_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transbtn_upActionPerformed
        // TODO add your handling code here:
        try{
            transaksi tran = new transaksi();
            tran.id_transaksi = Integer.parseInt(txt_idtrans.getText());
            this.stat = k.getCon().prepareStatement("update transaksi set nama_pelanggan=?," + "id_barang=?,tanggal=?,nama_barang=?,harga=?,jumlah_beli=?,total_bayar=? " + "where id_transaksi=?");
            this.stat.setString(1, tran.nama_pelanggan);
            this.stat.setInt(2, tran.id_barang);
            this.stat.setString(3, tran.tanggal);
            this.stat.setString(4, tran.nama_barang);
            this.stat.setInt(5, tran.harga);
            this.stat.setInt(6, tran.jumlah_beli);
            this.stat.setInt(7, tran.total_bayar);
            this.stat.setInt(8, tran.id_transaksi);
            this.stat.executeUpdate();
            refreshTable();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_transbtn_upActionPerformed

    private void transbtn_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transbtn_delActionPerformed
        // TODO add your handling code here:
        try{
            transaksi tran = new transaksi();
            tran.id_transaksi = Integer.parseInt(txt_idtrans.getText());
            this.stat = k.getCon().prepareCall("delete from transaksi " + "where id_transaksi=?");
            this.stat.setInt(1, tran.id_transaksi);
            this.stat.executeUpdate();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_transbtn_delActionPerformed

    private void btn_lihbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lihbarActionPerformed
        // TODO add your handling code here:
        Barang brng = new Barang();
        brng.setVisible(true);
        this.setVisible(false);
        brng.brgbtn_in.setEnabled(true);
        brng.brgbtn_del.setEnabled(true);
        brng.brgbtn_up.setEnabled(true);
        brng.brgbtn_mt.setEnabled(true);
    }//GEN-LAST:event_btn_lihbarActionPerformed

    private void bobox_idbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bobox_idbarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bobox_idbarActionPerformed

    private void txt_totbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totbarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totbarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> bobox_idbar;
    private javax.swing.JButton btn_lihbar;
    private com.toedter.calendar.JCalendar jCalendar1;
    private com.toedter.calendar.JCalendar jCalendar2;
    private com.toedter.calendar.JDayChooser jDayChooser1;
    private com.toedter.calendar.JDayChooser jDayChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton transbtn_cetlap;
    private javax.swing.JButton transbtn_del;
    private javax.swing.JButton transbtn_in;
    private javax.swing.JButton transbtn_log;
    private javax.swing.JButton transbtn_up;
    private javax.swing.JTable transtbl;
    private javax.swing.JTextField txt_idtrans;
    private javax.swing.JTextField txt_jumbar;
    private javax.swing.JTextField txt_pelang;
    private com.toedter.calendar.JDateChooser txt_tgl;
    private javax.swing.JTextField txt_totbar;
    // End of variables declaration//GEN-END:variables
}
